version: '3'

services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=z-games
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpass123

  api:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 4000:4000
    depends_on:
      - database
